### ISSUE TITLE
Anchor links do not take into account the top navigation bar

### ISSUE THREAD

**Issue by josh146** [XanaduAI/xanadu-sphinx-theme#3]
When clicking anchor links to docstrings in the Xanadu Sphinx Theme, Sphinx is ignoring the height of the navbar.

This leads to the top of the section being cut off.

For example, consider the following link: https://pennylane--2450.org.readthedocs.build/en/2450/code/api/pennylane.cut_circuit.html?highlight=cut_circuit#pennylane.cut_circuit

The page will load like this:

![image](https://user-images.githubusercontent.com/2959003/163882621-8e82e528-eeb3-455e-a52b-b92c99b418d1.png)

Rather than like this:

![image](https://user-images.githubusercontent.com/2959003/163882720-a5226cba-2ce4-4482-b1fa-c56cc6b56e17.png)

**Comment by Mandrenkov** [comment]
Nice catch! 🎣 As noted by @AndrewGardhouse, the issue has to do with MathJax: the screen would scroll to the anchor but then MathJax would render afterwards and change the scroll positioning. The fix is a small JS snippet to be implemented by #2.

**Comment by josh146** [comment]
> MathJax would render afterwards and change the scroll positioning

🤯
