### ISSUE TITLE
"View on Github" link for gallery items is broken

### ISSUE THREAD

**Issue by RioWeil** [XanaduAI/xanadu-sphinx-theme#39]
(Apologies in advance that this does not fit the bug issue template - this seems to no longer exist)

When clicking the "View on Github" link (under downloads) for gallery entries, instead of taking users to the source code of the page in the GitHub repository, users are instead taken to a "Not Found" page; for example the link in this tutorial demo page https://xanadu-sphinx-theme.readthedocs.io/en/latest/gallery/tutorial_demo.html.

A potential fix may be the appropriate modification to `githubLink` and `github-view-link` in `layout.html`.

**Comment by josh146** [comment]
Thanks for catching this @RioWeil! I think this should be as easy as adding the `github_repo` config setting

https://github.com/XanaduAI/xanadu-sphinx-theme/blob/237ab9e456717a40e0725eabe02a278e552a689e/xanadu_sphinx_theme/theme.conf#L56-L58

to the `conf.py` file here:

https://github.com/XanaduAI/xanadu-sphinx-theme/blob/237ab9e456717a40e0725eabe02a278e552a689e/doc/conf.py#L101

**Comment by RioWeil** [comment]
Great, I'll give that a try - thanks for the suggestion and quick reply!
