### ISSUE TITLE
Change to more aesthetic math rendering 💅🏼 

### ISSUE THREAD

**Issue by soosub** [XanaduAI/xanadu-sphinx-theme#6]
### Feature details

[FlamingPy](https://flamingpy.readthedocs.io/en/latest/index.html) uses this Xanadu Sphinx theme on our readthedocs pages, but the math rendering is not pleasant to read since it results in pixelated equations, see [this QEC explainer](https://flamingpy.readthedocs.io/en/latest/quantum_error_correction.html) for example. This happens because the equations are rendered as a png. I would propose to change this to the way StrawberryFields and PennyLane do it, see [this paragraph](https://pennylane.readthedocs.io/en/stable/introduction/measurements.html#tensor-observables) on tensor observables.

### Implementation

PennyLane and StrawberryFields already use the proposed method. I guess it's relatively easy to change the general Xanadu theme accordingly.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by josh146** [comment]
Hey @soosub! This is a bit confusing, since PL and SF both use this general theme as well. Maybe they do something different in their `conf.py` configuration files?

**Comment by soosub** [comment]
Alright, I'll have a look and keep you posted @josh146

**Comment by soosub** [comment]
Found it! Apparently we had both `sphinx.ext.imgmath` and `sphinx.ext.mathjax` in the `extensions` of the ` conf.py` file. Removing `sphinx.ext.imgmath` did the trick 👌🏼

Thanks @josh146!
